/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectouniversidadulp.vistas;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmFormMaterias = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmFormAlumnos = new javax.swing.JMenuItem();
        jmIns = new javax.swing.JMenu();
        jmInscribir = new javax.swing.JMenuItem();
        jmDesinscribir = new javax.swing.JMenuItem();
        jmCargaNotas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmCons = new javax.swing.JMenu();
        jMenuItemVistaAlumnosPorMaterias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jmArchivo.setText("Archivo");

        jmSalir.setText("Salir");
        jmArchivo.add(jmSalir);

        jMenuBar1.add(jmArchivo);

        jmMateria.setText("Materias");

        jmFormMaterias.setText("Formulario de Materias");
        jmFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormMateriasActionPerformed(evt);
            }
        });
        jmMateria.add(jmFormMaterias);

        jMenuBar1.add(jmMateria);

        jmAlumno.setText("Alumnos");

        jmFormAlumnos.setText("Formulario de Alumnos");
        jmFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormAlumnosActionPerformed(evt);
            }
        });
        jmAlumno.add(jmFormAlumnos);

        jMenuBar1.add(jmAlumno);

        jmIns.setText("Inscripciones");

        jmInscribir.setText("Inscribir");
        jmInscribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmInscribirMouseClicked(evt);
            }
        });
        jmInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInscribirActionPerformed(evt);
            }
        });
        jmIns.add(jmInscribir);

        jmDesinscribir.setText("Desinscribir");
        jmDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDesinscribirActionPerformed(evt);
            }
        });
        jmIns.add(jmDesinscribir);

        jMenuBar1.add(jmIns);

        jmCargaNotas.setText("Carga de Notas");

        jMenuItem2.setText("Manipulacion de notas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmCargaNotas.add(jMenuItem2);

        jMenuBar1.add(jmCargaNotas);

        jmCons.setText("Consultas");

        jMenuItemVistaAlumnosPorMaterias.setText("Listado de alumnos por Materia");
        jMenuItemVistaAlumnosPorMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVistaAlumnosPorMateriasActionPerformed(evt);
            }
        });
        jmCons.add(jMenuItemVistaAlumnosPorMaterias);

        jMenuBar1.add(jmCons);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        
        VistaAlumno va= new VistaAlumno();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_jmFormAlumnosActionPerformed

    private void jmInscribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmInscribirMouseClicked
        // TODO add your handling code here:
        VistaAltaInscripcion vai = new VistaAltaInscripcion();
        vai.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vai);
        escritorio.moveToFront(vai);
    }//GEN-LAST:event_jmInscribirMouseClicked

    private void jmInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInscribirActionPerformed
        // TODO add your handling code here:
        VistaAltaInscripcion vai = new VistaAltaInscripcion();
        vai.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vai);
        escritorio.moveToFront(vai);
    }//GEN-LAST:event_jmInscribirActionPerformed

    private void jmDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDesinscribirActionPerformed
        // TODO add your handling code here:
        VistaBajaInscripcion vbi = new VistaBajaInscripcion();
        vbi.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vbi);
        escritorio.moveToFront(vbi);
    }//GEN-LAST:event_jmDesinscribirActionPerformed

    private void jMenuItemVistaAlumnosPorMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVistaAlumnosPorMateriasActionPerformed
        // TODO add your handling code here:       
        VistaAlumnosPorMateria vapm = new VistaAlumnosPorMateria();
        vapm.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vapm);
        escritorio.moveToFront(vapm);
        
    }//GEN-LAST:event_jMenuItemVistaAlumnosPorMateriasActionPerformed

    private void jmFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormMateriasActionPerformed
        // TODO add your handling code here:
           VistaMateria vam = new VistaMateria();
        vam.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vam);
        escritorio.moveToFront(vam);
        
        
    }//GEN-LAST:event_jmFormMateriasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VistaCargarNota vcn = new VistaCargarNota();
        vcn.setVisible(true);
        
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemVistaAlumnosPorMaterias;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmCargaNotas;
    private javax.swing.JMenu jmCons;
    private javax.swing.JMenuItem jmDesinscribir;
    private javax.swing.JMenuItem jmFormAlumnos;
    private javax.swing.JMenuItem jmFormMaterias;
    private javax.swing.JMenu jmIns;
    private javax.swing.JMenuItem jmInscribir;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
